### PR TITLE
Complete no output generic update

### PR DESCRIPTION
**Pull request by jamwaffles**
Closes #14 with changes from [this gist](https://gist.github.com/jamwaffles/a98d2ba3a445866d4084cb2f2f1aa3e8).

### CODE REVIEW

**Comment by jamwaffles** [comment]
Hey @pferreir do you have a quick piece of example code I can throw in a `#[test]` to ensure this does what you want it to do? 

P.s. I hope I'm not stepping on your toes by opening this over #14 - I just had it on my TODO for a while and wanted to get it over the line.

**Comment by jamwaffles** [comment]
`NoOutputPin` usage looks like this:

```rust
let mut disp: GraphicsMode<_> = Builder::new()
    .connect_spi(spi, dc, sh1106::builder::NoOutputPin::new())
    .into();
```

I had to add a `new()` method as it uses `PhantomData` so can't be created like `sh1106::builder::NoOutputPin`.

**Comment by pferreir** [comment]
@jamwaffles no problem. Thanks for completing this. I haven't had much free time these days.

As for the test, I believe the main point was to allow for arbitrary `Error` types. This should be enough:

```rust
#[cfg(test)]
mod tests {
    use embedded_hal::digital::v2::OutputPin;
    use super::NoOutputPin;

    enum SomeError {}

    struct SomeDriver<P: OutputPin<Error = SomeError>> {
        #[allow(dead_code)]
        p: P
    }

    #[test]
    fn test_output_pin() {
        let p = NoOutputPin::new();
        let _d = SomeDriver { p };

        assert!(true);
    }
}
```

**Comment by jamwaffles** [comment]
This is released in version [0.3.0-alpha.3](https://crates.io/crates/sh1106/0.3.0-alpha.3).

**Pull request merged**
